project:
  type: website

website:
  title: "Gerko Vink"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: mywork.qmd
        text: My Work banana

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



